name: Playwright Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'

      # --- Paso para instalar Java (JDK) - Necesario para Allure ---
      - name: Instalar Java (JDK) para Allure
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # Usamos Temurin, una distribución OpenJDK confiable
          java-version: '17'      # Se recomienda Java 11 o superior para Allure 2.x

      # --- Paso para instalar Allure Commandline Tool ---
      - name: Instalar Allure Commandline Tool
        run: |
          ALLURE_VERSION="2.29.0" # ¡ACTUALIZA ESTA VERSIÓN REGULARMENTE!
          ALLURE_INSTALL_DIR="${HOME}/allure-cli" # Instalar en el directorio home del runner, donde hay permisos de escritura
          
          mkdir -p "${ALLURE_INSTALL_DIR}"
          curl -sL https://github.com/allure-framework/allure2/releases/download/${ALLURE_VERSION}/allure-${ALLURE_VERSION}.tgz -o allure-commandline.tgz
          tar -xzf allure-commandline.tgz -C "${ALLURE_INSTALL_DIR}" --strip-components=1 # Descomprime y elimina la carpeta raíz del tar
          
          echo "${ALLURE_INSTALL_DIR}/bin" >> $GITHUB_PATH # Añade Allure al PATH para pasos subsiguientes

      # --- Verificación de la instalación de Allure (en un paso separado para asegurar el PATH) ---
      - name: Verificar instalación de Allure
        run: allure --version # Este comando ahora debería funcionar

      - name: Instalar dependencias de Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 
      
      - name: Instalar navegadores de Playwright
        run: playwright install --with-deps

      # --- Ejecutar pruebas con Pytest y generar resultados para Allure ---
      - name: Ejecutar pruebas de Playwright y generar resultados de Allure
        run: |
          # Asegúrate de que las rutas a tus tests sean correctas dentro de 'at-practice/test/'
          # Los resultados crudos de Allure se guardarán en test/reportes/allure-results
          pytest at-practice/test/test_login.py \
                 at-practice/test/test_home.py \
                 at-practice/test/test_producto.py \
                 at-practice/test/test_carrito.py \
                 at-practice/test/test_menu.py \
                 --alluredir=at-practice/test/reportes/allure-results 

      # --- Paso para generar el reporte HTML de Allure ---
      - name: Generar Reporte Allure HTML
        run: |
          # Genera el reporte HTML desde los resultados crudos
          # El reporte final se guardará en test/reportes/allure-report
          allure generate at-practice/test/reportes/allure-results --clean -o at-practice/test/reportes/allure-report
      
      # --- Subir el reporte de Allure como un artefacto ---
      - name: Subir Reporte Allure
        uses: actions/upload-artifact@v4
        if: always() # Siempre sube el reporte, incluso si las pruebas fallan
        with:
          name: playwright-allure-report
          path: at-practice/test/reportes/allure-report/ 
          retention-days: 30